_config/lib: !include "../config/hpack-common.yaml"

name:       luna-shell
version:    "1.2"
author:     Luna Team <contact@luna-lang.org>
maintainer:
    - Wojciech Danilo  <wojciech.danilo@luna-lang.org>
    - Marcin Kostrzewa <marcin.kostrzewa@luna-lang.org>
    - Ara Adkins       <ara.adkins@luna-lang.org>

library:
    source-dirs:
        - src
    dependencies:
        - aeson
        - base
        - bimap
        - containers
        - directory
        - filepath
        - githash
        - layered-state
        - lens
        - luna-core
        - luna-datafile
        - luna-exception
        - luna-package
        - luna-passes
        - luna-runtime
        - luna-stdlib
        - megaparsec
        - mtl
        - optparse-applicative
        - path
        - prologue
        - safe-exceptions
        - text
        - unordered-containers
        - yaml

executables:
    luna:
        main: src-app/Main.hs
        when:
            - condition: os(darwin)
              then:
                  # We need the no-nonportable-include-path on MacOS because of an issue
                  # in cabal: https://github.com/haskell/cabal/issues/4739.
                  ghc-options: -threaded "-with-rtsopts=-N -T" "-optP-Wno-nonportable-include-path"
              else:
                  ghc-options: -threaded "-with-rtsopts=-N -T"
        dependencies:
            - base
            - luna-shell
            - prologue

benchmarks:
    interpreter-benchmark:
        main: Main.hs
        source-dirs:
            - test/bench
        ghc-options:
            - -rtsopts
            - -threaded
            - -with-rtsopts=-N
            - -with-rtsopts=-T
        dependencies:
            - base
            - directory
            - filepath
            - luna-datafile
            - luna-exception
            - luna-package
            - luna-shell
            - path
            - prologue
            - template-haskell

default-extensions: *luna-extensions

